In [14]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [15]:
data = pd.read_csv('cardio_train1.csv')
data.head()

id    age  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  smoke  \
0   0  18393       2     168    62.0    110     80            1     1      0   
1   1  20228       1     156    85.0    140     90            3     1      0   
2   2  18857       1     165    64.0    130     70            3     1      0   
3   3  17623       2     169    82.0    150    100            1     1      0   
4   4  17474       1     156    56.0    100     60            1     1      0   

   alco  active  cardio  
0     0       1       0  
1     0       1       1  
2     0       0       1  
3     0       1       1  
4     0       0       0

In [16]:
data.isna().sum()

id             0
age            0
gender         0
height         0
weight         0
ap_hi          0
ap_lo          0
cholesterol    0
gluc           0
smoke          0
alco           0
active         0
cardio         0
dtype: int64

In [17]:
X = data.iloc[:, 1:-1]
y = data.iloc[:, -1]

In [18]:
from sklearn.preprocessing import MinMaxScaler
mms = MinMaxScaler()
X = mms.fit_transform(X)

In [19]:
X

array([[0.58807588, 1.        , 0.57948718, ..., 0.        , 0.        ,
        1.        ],
       [0.73015873, 0.        , 0.51794872, ..., 0.        , 0.        ,
        1.        ],
       [0.6240031 , 0.        , 0.56410256, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.64018583, 1.        , 0.65641026, ..., 0.        , 1.        ,
        0.        ],
       [0.90073558, 0.        , 0.55384615, ..., 0.        , 0.        ,
        0.        ],
       [0.75431669, 0.        , 0.58974359, ..., 0.        , 0.        ,
        1.        ]], shape=(70000, 11))

In [20]:
np.shape(X)

(70000, 11)

In [21]:
y = pd.get_dummies(y)

In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=400)

In [23]:
model = tf.keras.models.Sequential([
    tf.keras.Input(shape=(11,)),
    tf.keras.layers.Dense(11, activation='relu'),
    tf.keras.layers.Dense(30, activation='relu'),
    tf.keras.layers.Dense(2, activation='softmax')
])

In [24]:
model.compile(
    optimizer=tf.keras.optimizers.Adam(0.001),
    loss=tf.keras.losses.CategoricalCrossentropy(),
    metrics=[tf.keras.metrics.CategoricalAccuracy()]
)

In [25]:
model.fit(X_train, y_train, epochs=10, validation_data=(X_test, y_test), batch_size=800)

Epoch 1/10
66/66 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - categorical_accuracy: 0.5408 - loss: 0.6892 - val_categorical_accuracy: 0.5741 - val_loss: 0.6828
Epoch 2/10
66/66 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.5789 - loss: 0.6768 - val_categorical_accuracy: 0.5869 - val_loss: 0.6716
Epoch 3/10
66/66 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.5953 - loss: 0.6644 - val_categorical_accuracy: 0.6089 - val_loss: 0.6561
Epoch 4/10
66/66 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.6125 - loss: 0.6517 - val_categorical_accuracy: 0.6282 - val_loss: 0.6465
Epoch 5/10
66/66 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.6290 - loss: 0.6431 - val_categorical_accuracy: 0.6345 - val_loss: 0.6388
Epoch 6/10
66/66 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.6364 - loss: 0.6372 - val_categorical_accuracy: 0.6393 - val_loss: 0.6342
Epoch 7/10
66/66 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.6396 - loss: 0.6340 - va

In [26]:
from sklearn.ensemble import RandomForestClassifier
yr = data.iloc[:, -1]

In [27]:
np.unique(yr, return_counts=True)

(array([0, 1]), array([35021, 34979]))

In [28]:
rfc = RandomForestClassifier(n_estimators=200)
Xr_train, Xr_test, yr_train, yr_test = train_test_split(X, yr, random_state=33123)

In [29]:
rfc.fit(Xr_train, yr_train)

RandomForestClassifier(n_estimators=200)

In [30]:
from sklearn.metrics import classification_report

In [31]:
y_pred = rfc.predict(Xr_test)
print(classification_report(y_true=yr_test, y_pred=y_pred))

              precision    recall  f1-score   support

           0       0.70      0.72      0.71      8652
           1       0.72      0.70      0.71      8848

    accuracy                           0.71     17500
   macro avg       0.71      0.71      0.71     17500
weighted avg       0.71      0.71      0.71     17500



In [32]:
model = tf.keras.models.Sequential([
    tf.keras.Input(shape=(11,)),
    tf.keras.layers.Dense(11, activation='relu'),
    tf.keras.layers.Dense(30, activation='relu'),
    tf.keras.layers.Dense(60, activation='relu'),
    tf.keras.layers.Dense(25, activation='relu'),
    tf.keras.layers.Dense(2, activation='softmax')
])
model.compile(optimizer=tf.keras.optimizers.Adam(0.001), loss=tf.keras.losses.CategoricalCrossentropy(), metrics=[tf.keras.metrics.CategoricalAccuracy()])

In [33]:
model.fit(X_train, y_train, epochs=500, validation_data=(X_test, y_test), batch_size=300)

Epoch 1/500
175/175 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - categorical_accuracy: 0.6016 - loss: 0.6581 - val_categorical_accuracy: 0.6294 - val_loss: 0.6424
Epoch 2/500
175/175 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.6302 - loss: 0.6407 - val_categorical_accuracy: 0.6341 - val_loss: 0.6371
Epoch 3/500
175/175 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.6360 - loss: 0.6357 - val_categorical_accuracy: 0.6403 - val_loss: 0.6318
Epoch 4/500
175/175 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.6391 - loss: 0.6334 - val_categorical_accuracy: 0.6419 - val_loss: 0.6299
Epoch 5/500
175/175 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.6422 - loss: 0.6310 - val_categorical_accuracy: 0.6425 - val_loss: 0.6287
Epoch 6/500
175/175 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.6436 - loss: 0.6293 - val_categorical_accuracy: 0.6415 - val_loss: 0.6279
Epoch 7/500
175/175 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.644

In [34]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_9 (Dense)                 │ (None, 11)             │           132 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 30)             │           360 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 60)             │         1,860 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_12 (Dense)                │ (None, 25)             │         1,525 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ (None, 2)              │            52 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 11,789 (46.05 KB)

 Trainable params: 3,929 (15.35 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 7,860 (30.71 KB)

In [35]:
model.predict(X_test)[5]

547/547 ━━━━━━━━━━━━━━━━━━━━ 0s 681us/step


array([0.7350954, 0.2649046], dtype=float32)

به احتمال 26 درصد بیماری داره به احتمال 73 درصد بیماری نداره پس میگیم بیماری داره